### ISSUE TITLE
Dedicated page to help users with newly claimed nodes that are not connecting to cloud

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/learn#1080]
## Description

Linked from here https://github.com/netdata/netdata-cloud/issues/471

As mentioned in the above issue, there are multiple scenarios in which newly claimed nodes show up as offline in Netdata cloud and there is no information to the user either in the cloud UI or in the logs that they can use to figure out what the problem is or fix this and truly connect these nodes to the cloud. 

As part of https://github.com/netdata/cloud-frontend/issues/3594 we are fixing this in the UI, but there must be a doc page that provides all the necessary information the user would need to be able to connect their nodes to the cloud that the UI can link to.

**Comment by Ancairon** [comment]
Hey @shyamvalsan I made a draft version, [here](https://github.com/Ancairon/netdata/blob/troubleshooting-agent-with-cloud-connection/docs/guides/troubleshoot/troubleshooting-agent-with-cloud-connection.md) but on my machine I can't test the ingest function to see if it will land on the correct spot on Learn, so that's why I am not opening a PR right away. As soon as I figure out what's going on with the ingest script and my setup I will make a PR

**Comment by tkatsoulas** [comment]
Great effort @Ancairon. @shyamvalsan Sorry for not reaching you earlier but I think this troubleshooting guide has no point. 

The claim process either work or not. Any problem regards to the claiming process should be communicated by error messages in place. 

The only info that we should update in our docs is:

> Claiming on an older, deprecated version of the Agent

With the introduction of our new architecture, Agents running versions lower than v1.32.0 can face this problem, so we reccomend to [update the Netdata Agent](https://learn.netdata.cloud/docs/agent/packaging/installer/update).

And to be more specific, we should add an admonition in the following docs:

1. https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#connect-node-to-netdata-cloud-during-installation
2. https://learn.netdata.cloud/docs/agent/claim

**Comment by shyamvalsan** [comment]
Hey @tkatsoulas we are adding some functionality to detect which nodes and for what reason couldn't connect to cloud post claim - and we want to show some the appropriate documentation. 

There will be a new indication in the UI for newly claimed but never-connected nodes. And that's what will bring us to this doc.

**Comment by shyamvalsan** [comment]
For further reference see comment https://github.com/netdata/netdata/issues/13294#issuecomment-1174706730

**Comment by shyamvalsan** [comment]
And there's roughly 150 such newly claimed but never connected nodes PER DAY - so anything we can do to reduce this whether that's via error messages, info on the UI, docs etc. is useful and required IMO.
