### ISSUE TITLE
Introduce a way to integrate our swagger API docs in Learn

### ISSUE THREAD

**Issue by Ancairon** [netdata/learn#1209]
## Description

I'm working on pull request/ issue:
#1207 

We can use [this plugin](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs) to generate MDX files from a .yaml file. This way the documents will be rendered in a UI similar to Swagger's, even allowing users to run the API queries.

This method uses a plugin and a theme, to properly render the API doc pages. It is just an extended version of the theme we used previously.

**Comment by cakrit** [comment]
Let's look at this again.

**Comment by andrewm4894** [comment]
hey - i think you can just do something like this: 

https://github.com/LAION-AI/Open-Assistant/tree/main/docs/docs/api
end up like this:
https://projects.laion.ai/Open-Assistant/api

config needs this https://github.com/LAION-AI/Open-Assistant/blob/main/docs/docusaurus.config.js#L39

**Comment by andrewm4894** [comment]
Think would just need the ingest script to also ingest the openapi json from netdata/netdata and this should be handy to do.

**Comment by Ancairon** [comment]
After discussion, we decided to go with [Swagger UI](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md) and host that as a separate instance.

I was able to deploy it in Docker, using a command similar to this:

```bash
docker run -d -p 80:8080 -e SWAGGER_JSON=/mnt/api.json -v /path/to/json/:/mnt swaggerapi/swagger-ui
```

I think next we have to look at deployment options, as I don't think Netlify supports Docker containers (and containers seem to be the easiest way to deploy swagger).

@cakrit
