### ISSUE TITLE
remove duplicate get started

### ISSUE THREAD

**Issue by cakrit** [netdata/learn#1299]
Find where https://learn.netdata.cloud/docs/cloud/get-started is located, move any info that we may be missing from the proper get started and DELETE IT.

**Comment by Ancairon** [comment]
I read the file, it is located here: https://github.com/netdata/netdata/blob/master/docs/cloud/get-started.mdx
And I don't see something that isn't stated somewhere already in our nightly docs.

If @hugovalente-pm is also aligned with this deletion, I will move forward removing the doc

**Comment by hugovalente-pm** [comment]
I also don't see an issue with it being removed but curious on what is our current get-started, is it these two? https://learn.netdata.cloud/docs/nightly/getting-started/introduction and https://learn.netdata.cloud/docs/nightly/getting-started/install-netdata

I see a lot of relevant information on the first and on the second really focused on installing the agent. I didn't find any place where we would suggest/nudge the user to connect the nodes to Cloud https://learn.netdata.cloud/docs/agent/claim

**Comment by Ancairon** [comment]
I think with the recent update to the "Install Netdata" doc (the old get-started.md) we aim to instruct the user to install _and_ claim, and then giving the other install options.

> I didn't find any place where we would suggest/nudge the user to connect the nodes to Cloud https://learn.netdata.cloud/docs/agent/claim

This page is now this one, so we have that info too. https://learn.netdata.cloud/docs/nightly/setup/connect-agent-to-cloud

I will proceed on removing the document.
