### ISSUE TITLE
Document functions

### ISSUE THREAD

**Issue by cakrit** [netdata/learn#1307]
get the data from https://github.com/netdata/netdata/pull/13720 and add the info probably under developers, will see.

**Comment by Ancairon** [comment]
I see that we already have:

[Netdata Functions](https://github.com/netdata/netdata/blob/master/docs/cloud/netdata-functions.md)
[Runtime troubleshooting with functions](https://github.com/netdata/netdata/blob/master/docs/cloud/runtime-troubleshooting-with-functions.md)

@cakrit
