### ISSUE TITLE
Idea: a single page dedicated just to setting up scalable parents.

### ISSUE THREAD

**Issue by andrewm4894** [netdata/learn#1385]
> We need a single page dedicated just to setting up scalable parents.

https://netdata-cloud.slack.com/archives/CNH27EEHY/p1676974432044979

**Comment by cakrit** [comment]
We'll be doing this with a reorg of the material in 
- https://docs.google.com/document/d/1g29mhFQ0LEyHtHegg6OCZUyRQzhNtW7pn7s-z5EfjGI/edit#heading=h.pes33yfifu11
- https://blog.netdata.cloud/why-is-data-replication-important/
- https://github.com/netdata/netdata/blob/master/streaming/README.md
- https://github.com/netdata/netdata/blob/master/docs/metrics-storage-management/reference-streaming.md

**Comment by cakrit** [comment]
The following is where the work for this needs to be done, the other docs are already updated and content moved where it needs to be:

https://learn.netdata.cloud/docs/deployment-in-production/streaming-and-replication/#supported-streaming-configurations
which comes from
https://github.com/netdata/netdata/blob/master/docs/metrics-storage-management/enable-streaming.md

We need to decide which use cases we'll present, to replace what we show today.

Common across all use cases: 
- Cloud will appear in every use case, with some explanations.
- Parent engine is always dbengine
- Parents always run alarms for the children, even if they also run alarms
- Parents are always connected to the cloud
- Proxies never have databases and aren't connected to cloud

Description |  Child database | Child alert checks | Child connected to cloud | Child has web UI | Upstream set up
-- | -- | -- | -- | -- | --
Simple non ephemeral set up | dbengine | Yes | Yes | Yes | A single parent
Ephemeral set up with active-active parents | ram | No | No | No | Two active-active parents, children streaming to one of the two at any time
Two different DMZs with proxies in the middle | dbengine | No | No | Yes | One proxy for each DMZ streaming to two active-active parents.

**Comment by cakrit** [comment]
![Simple parent child](https://user-images.githubusercontent.com/43294513/228891775-0465ffab-1210-406b-b733-d626fd0c10d0.jpg)



![Simple parent child no cloud](https://user-images.githubusercontent.com/43294513/228891897-aec7f7e1-172f-4ff1-b52d-209f59dc7125.jpg)



![Ephemeral nodes with two parents](https://user-images.githubusercontent.com/43294513/228891974-590bf0de-4e5a-46b2-a07a-7bb3dffde2bf.jpg)

**Comment by cakrit** [comment]
- Add where ML runs.

**Comment by cakrit** [comment]
For the supported options just leave the roles described. Proxy parent child.
The architecture diagrams will be for recommended options, which only have the cloud.

- One parent has children as backup for HA
- Two parents for HA and potentially border gateway protect production infra.

**Comment by cakrit** [comment]
1. Minimum: add a parent and connect the parent to the cloud
 - You can optimize children, but we suggest then to add a second parent.

2. For HA add another parent and slim down the children.

3. Mutlicloud. Take the other two and show them in multiple clouds.

**Comment by cakrit** [comment]
1million metrics/sec with 16cores and 32GB RAM.

**Comment by cakrit** [comment]
The diagrams have been updated. 

A section was added to https://github.com/netdata/netdata/blob/master/docs/store/change-metrics-storage.md as well.

PRs merged, learn will be updated today.
