### ISSUE TITLE
Automate the addition of redirects, every time content is moved or renamed

### ISSUE THREAD

**Issue by cakrit** [netdata/learn#1466]
Whenever we change an entry in `map.tsv`, we should automatically add or modify related entries in `LegacyLearnCorrelateLinksWithGHURLs.json` to ensure we don't get new 404s.

**Comment by cakrit** [comment]
cc @tkatsoulas

**Comment by tkatsoulas** [comment]
We already do this ([sample](https://github.com/netdata/learn/pull/1459#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489edR651-R680)). All the Links from the legacy learn for which markdown files exist (or are mapped to something similar, but always an alive markdown file).  There is only one case that we don't cover in the `ingest/autogenerateRedirects` (to make the process whole):

A document lived for a certain period (let's say under link A). If we change it to something else (call it B) after N months we 
 will update any current redirects that, by their origin* where point to A to B  but we will not add a redirect from A->B where don't have a process to keep track of this transition. 

This will also affect (in a positive way) new files that were never part of the "Legacy" learn.

I will implement this alongside some other improvements asap.

**Comment by cakrit** [comment]
New structure of `netlify.toml`:

```
#  START: Recent auto redirects from changes in map.tsv (coming from map-redirects.toml)
   ## START: [YYYYMMDD]-[something unique] Newest run entries are at the top
    ... redirect ...
   ## END:  [YYYYMMDD]-[something unique]
# END: Recent auto redirects


# START: Static manual redirects (coming from static-netlify.toml)
# Only manual directory or complex redirects are allowed here (e.g. :splat)
... redirect ...
# END: Static manual redirects 


# START: JSON redirects (coming from LegacyLearnCorrelateLinksWithGHURLs.json)
Exclusively contains single file redirects.
# END: JSON redirects

```
