### ISSUE TITLE
Link checks miss some links to learn.netdata.cloud

### ISSUE THREAD

**Issue by cakrit** [netdata/learn#1486]
See
https://learn.netdata.cloud/docs/data-collection/monitor-anything/System%20Metrics/Windows-machines#requirements

<img width="580" alt="image" src="https://user-images.githubusercontent.com/43294513/224340998-d11c9e39-9cef-418c-b81d-f5fea4634786.png">

This should have been caught by ingest.py as an error, to be fixed. Use it to test, and fix all such links after ingest learns to detect them and fail if they exist.

**Comment by Ancairon** [comment]
This link and the one right after it are also Learn links, let me see how I can tackle this.
