### ISSUE TITLE
Description tag of every Doc should be from 110 to 160 characters

### ISSUE THREAD

**Issue by Ancairon** [netdata/learn#1546]
## Description

Related to: #1507 

This is related to an ahrefs issue, it reports a lot of documents with short descriptions, and some with very long ones.

The very short ones have `meta` description coming from the `description:` metadata that lives in our map

The very long ones have the first block of text (before a line break it seems) as a description by default, they don't have a `description` metadata

if there is no Docusuaurs `description:` the first block of text ([here](https://learn.netdata.cloud/docs/data-collection/monitor-anything/Netdata/Alarms) for example ahrefs reports that the whole block is a description, so maybe we need a line break to limit it to the first few sentences) of the document gets assigned as `meta` description, that is then used for search engine stuff.

One point that I have is: 
would it be better to have the description inside the file, so we don't have to maintain two descriptions? Some files have very nice description metadata and then a single line inside the actual file. So the user sees one line, and the search engine the proper description.

If we removed the description metadata and kept the first block of text in a file to serve as a description, 110-160 characters long, then both search engines and users would get valuable information about what the file is about.

@cakrit

**Comment by cakrit** [comment]
Yes, I like this idea. I've done this short description in the beginning in a few files. It's a lot of work, but it's worth it.
