### ISSUE TITLE
Make the top navbar the same as www.netdata.cloud

### ISSUE THREAD

**Issue by cakrit** [netdata/learn#1621]
We have decided to provide almost the same navigation bar across our various websites, within reason. 
For learn, we will keep the search bar and the toggle between light/dark more, but we should make the rest look as much as the website as possible. 

An immediate and potentially valuable improvement is to add a Sign Up green button in addition to the Sign in. 
There are a lot of other easy to do things. Not sure if we can do the dropdowns the same way, we can look at that.

**Comment by andrewm4894** [comment]
It's not working on mobile 
![Screenshot_20230502-100329](https://user-images.githubusercontent.com/2178292/235625304-fd7cc1ba-f9d2-4ae2-94f3-c2f5a8b3b86a.png)

**Comment by Ancairon** [comment]
I am aware of this, this is a side effect we have explored way back with the searchbar, but the instruction was to copy exactly the navbar, @cakrit let's discuss

**Comment by Ancairon** [comment]
But another side effect happens if you shorten the width of the window, everything get's compressed and rendered a bit weirdly.
