### ISSUE TITLE
[Feedback]: macOS netdata agent not seeing windows exporter

### ISSUE THREAD

**Issue by jhgorse** [netdata/learn#1638]
### Doc Page link

https://www.netdata.cloud/windows-monitoring/#configure-netdata-to-monitor-windows
and
https://learn.netdata.cloud/docs/data-collection/monitor-anything/system-metrics/windows-machines#configuration

### Description

I have a macOS netdata agent which is connected to the cloud. It works.

I have a windows machine with prometheus exporter installed and running. It works. I can access http://windows_machine_ip:9182/metrics from macOS.

I have added 
```
jobs:
  - name: windows-hostname
    url: http://windows_machine_ip:9182/metrics
```
to `/usr/local/netdata/etc/netdata/go.d/windows.conf` via `/usr/local/netdata/etc/netdata/edit-config`
per the documentation.

In this document, https://learn.netdata.cloud/docs/data-collection/monitor-anything/system-metrics/windows-machines#configuration

it says, 
`Hint: Use friendly server names for job names, as these will appear as "instances" in Netdata Cloud charts and on the right side menu of the agent UI charts.`

As a new user, that statement is ambiguous. I see nothing that resembles the data which should be there for the windows machine, no differentiation of which Cloud charts nor agent UI charts.
<img width="1382" alt="image" src="https://github.com/netdata/learn/assets/1783474/ca439d21-3328-45fb-8ee0-3c2ba2ea5fe6">

Also recommend adding the steps needed to verify the netdata agent is attempting to pull the data from the windows host would be nice.

Cheers

**Comment by Ancairon** [comment]
Hey @jhgorse sorry for the late reply, I guess you have figured it by now, you were looking at the home tab of your dashboard. That doesn't show any charts.

You should be seeing your metrics on the overview tab, something similar to:

![image](https://github.com/netdata/learn/assets/70198089/883a74c5-7f68-4583-8b54-6fb3e722aa87)

As for:

>Also recommend adding the steps needed to verify the netdata agent is attempting to pull the data from the windows host would be nice.

You can run the collector in debug mode: https://learn.netdata.cloud/docs/data-collection/external-plugins/go.d.plugin/#troubleshooting

And you can also take a look at the integrations marketplace entry for this collector [link](https://app.netdata.cloud/spaces/netdata-demo/rooms/all-nodes/overview#metrics_correlation=false&after=-900&before=0&utc=Europe%2FAthens&offset=%2B3&timezoneName=E.%20Europe&modal=&modalTab=&modalParams=&selectedIntegrationCategory=data-collection.windows-systems&d8a4e0c5-7c79-4145-900e-83a9f06fcb6a--chartName=menu_system&integrationsModalOpen=true&selectedIntegrationTab=4&selectedIntegration=go.d.plugin-windows-Windows)

**Comment by jhgorse** [comment]
I never did solve this. Thanks for the debug tips. This is a note to future me @jhgorse to give this a spin and follow up.
