### ISSUE TITLE
Restructure docs 

### ISSUE THREAD

**Issue by cakrit** [netdata/learn#1641]
An [internal doc](https://docs.google.com/document/d/1llLdRTTldnR_lYy5fYMX-mXUt-bmEIqQ-sOVBMUFFd8/edit#heading=h.ew82dah2f22z) describes a new documentation structure for Learn. 

We need to start immediately with the changes in the data collection category, and then move to other sections.

High level guidelines:
- Tackle one high level category at a time, iteratively. No big bang.
- If a category does not exist today and is not immediately clear where it should lead, ask for clarifications in the doc itself. 
- If a page that exists currently does not appear at all in the new structure, mark it to ask in a call what should happen to it.

Some guidelines have already been provided for data collection:
- Where specific supported OSs like Redhat are mentioned and a page does not exist, lead them to the installation page
- Some new pages will need to be created e.g. to collect in one place everything we do for AWS or Google Cloud infrastructures. 
- In a future iteration, we will need to add collector metadata (csv, yaml, the whole thing) for every Prometheus endpoint that exists, even if we don't have default configs for it. The documentation of the charts and metrics should be generated from whatever is available publicly for each Prometheus endpoint
- A [JSON file](https://github.com/netdata/website/blob/master/data/integrations.json) is currently used for the categorization of pages on https://www.netdata.cloud/integrations. The changes we do in learn will precede the changes that will be done on that file. The hierarchy will become identical between learn and website. The links in the JSON will need to be updated to point directly to the published page in learn.

cc @lupimiguel @shyamvalsan

**Comment by Ancairon** [comment]
# Checklist

To restructure the docs, the following must happen in order:

- [ ] Merge category overview pages
- [ ] Deploy on staging for one last check
- [ ] Merge on master
- [ ] Ingest

**Comment by andrewm4894** [comment]
What are we going to do for redirects for old pages that we have linked to in blogs etc.
