### ISSUE TITLE
[Feedback]: Docs on host-editable configuration mistake volumes for bind mounts

### ISSUE THREAD

**Issue by putnam** [netdata/learn#1723]
### Doc Page link

https://learn.netdata.cloud/docs/installing/docker#host-editable-configuration

### Description

> If you want to make your container's configuration directory accessible from the host system, you need to use a [volume](https://docs.docker.com/storage/bind-mounts/) rather than a bind mount.

I believe this sentence is backwards. The default setup uses volumes. You need a bind mount in order to edit files in place on the host. The sentence should read "you need to use a bind mount rather than a volume".

I thought my brain was broken for a second there. The URL is correct (to bind mounts) so it's just the terms being swapped.

Furthermore, the recommendation on generating the config files so you can edit them on the host doesn't seem to work. If you just run the netdata/netdata image with a bind mount for /etc/netdata, it doesn't write any files. I thought this was default behavior since an unmodified stock config doesn't actually write any config files.

I know it should be a separate issue, but there's also no explanation for the purpose of SYS_PTRACE or the apparmor directives, only telling users to blindly copy/paste them. It would benefit everyone to know why these are needed and what breaks if they're not there.

**Comment by putnam** [comment]
It looks like README is also wrong here:
https://github.com/netdata/netdata/blob/master/packaging/docker/README.md#create-a-new-netdata-agent-container

The sentence:

> Both methods create a [bind mount](https://docs.docker.com/storage/bind-mounts/) for Netdata's configuration files within the container at /etc/netdata.

.. is at odds with the methods shown, both of which use volumes, not bind mounts.

**Comment by Ancairon** [comment]
Hello @putnam! Thanks for raising this issue!

> I believe this sentence is backwards. The default setup uses volumes. You need a bind mount in order to edit files in place on the host. The sentence should read "you need to use a bind mount rather than a volume".

Wow, yes this is rather strange, and it is indeed flipped.

>It looks like README is also wrong here:
[netdata/netdata@master/packaging/docker/README.md#create-a-new-netdata-agent-container](https://github.com/netdata/netdata/blob/master/packaging/docker/README.md?rgh-link-date=2023-07-03T05%3A10%3A59Z#create-a-new-netdata-agent-container)

Yup, the Learn file is a mirror of the netdata/netdata file. To make changes we need to edit the netdata/netdata, that's the source.

As for

>Furthermore, the recommendation on generating the config files so you can edit them on the host doesn't seem to work. If you just run the netdata/netdata image with a bind mount for /etc/netdata, it doesn't write any files. I thought this was default behavior since an unmodified stock config doesn't actually write any config files.

and

>I know it should be a separate issue, but there's also no explanation for the purpose of SYS_PTRACE or the apparmor directives, only telling users to blindly copy/paste them. It would benefit everyone to know why these are needed and what breaks if they're not there.

I would open two issues on netdata/netdata to get more eyes on both matters.

I will make a PR addressing the first issue.

**Comment by putnam** [comment]
It does not create the config files in the bind mount. The server starts
up, runs a default config, shuts down cleanly and never writes any files to
/etc/netdata. I used a bind mount with 777 perms just to be sure. The dot
files for the container hostname and disabling phone-home did get created
so it was able to write those.

**Comment by ilyam8** [comment]
Yes, a user is responsible for handling permission/ownership problems when using bind mounts. However, [Host-editable configuration](https://learn.netdata.cloud/docs/installing/docker#host-editable-configuration) works for me. It is:

 - create `netdataconfig` dir.
 - copy the content of (temporary) Netdata to the dir manually using `docker cp`.
 - stop/remove temporary Netdata, create a new one, and mount `netdataconfig` to it.

As you can see Netdata doesn't write any files. It only reads.

**Comment by putnam** [comment]
I’m sure I am misunderstanding something. The part where you copy the
contents — the contents of what? /etc/netdata, right? That’s empty (except
dot files) on a default fresh install as far as I can tell.

Even shelling in with docker exec to a running default instance, the
directory is empty. What files are you seeing?

**Comment by ilyam8** [comment]
Yes, `/etc/netdata`, right. No, it is not empty. Why would it be?

I checked the code and see that even this trick with temporary instance is not required (but it works) because:

- copy the stock `/etc/netdata` to `/etc/netdata.stock` in [Dockerfile](https://github.com/netdata/netdata/blob/55016fd5104e0f296cda84763edfa90034077546/packaging/docker/Dockerfile#L118)
- and copy it back if `/etc/netdata` is mounted and empty (on start) in [run.sh](https://github.com/netdata/netdata/blob/55016fd5104e0f296cda84763edfa90034077546/packaging/docker/run.sh#L49-L52) (entrypoint)

```bash
# empty dir on the host
$ ls -la netdataconfig/netdata/

# start ND and mount `netdataconfig/netdata/`
pve-deb-work ~ $ docker run -d --name=netdata \
  -p 19998:19999 \
  -v $(pwd)/netdataconfig/netdata:/etc/netdata \
  netdata/netdata
dc1a74fff62584f33a235069018042759322de259c6daf7c456acbade0515665

# netdataconfig/netdata/ has content
pve-deb-work ~ $ ls -la netdataconfig/netdata/
drwxr-xr-x    - root root 29 Jun 03:37 charts.d
drwxr-xr-x    - root root 29 Jun 03:37 custom-plugins.d
drwxr-xr-x    - root root 29 Jun 03:37 ebpf.d
drwxr-xr-x    - root root 29 Jun 03:37 go.d
drwxr-xr-x    - root root 29 Jun 03:37 health.d
drwxr-xr-x    - root root 29 Jun 03:37 python.d
drwxr-xr-x    - root root 29 Jun 03:37 ssl
drwxr-xr-x    - root root 29 Jun 03:37 statsd.d
.rw-r--r--   13 root root  4 Jul 11:03 .container-hostname
.rw-r--r--  558 root root 29 Jun 03:38 .environment
.rw-r--r--   42 root root 29 Jun 03:37 .install-type
.rwxr-xr-x 8.7k root root 29 Jun 03:37 edit-config
.rw-r--r--  208 root root 29 Jun 03:38 netdata.conf
lrwxrwxrwx   23 root root  4 Jul 11:03 orig -> /usr/lib/netdata/conf.d

```

**Comment by putnam** [comment]
Yeah, it bothers me to no end right now, but I now cannot repro the issue I
had. Works fine every time. Sorry for the false alarm. If I can repro it
I'll re-raise.

**Comment by Ancairon** [comment]
Wording fixed in https://github.com/netdata/netdata/pull/15298. Thanks @putnam for the feedback!
