### ISSUE TITLE
[Feedback]: pgbouncer collector documentation

### ISSUE THREAD

**Issue by pmbmarques** [netdata/learn#1738]
### Doc Page link

https://learn.netdata.cloud/docs/data-collection/database-servers/pgbouncer 

### Description

The file that should be in  edit is go.d/pgbouncer.conf and not go.d/postgresql.conf, I'am doing the configuration in netdata v1.40.0-131-nightly and i can not get stats from pgbouncer doing the config as is described in the learn page. 

Also, the command to debug the pgbouncer collector should be ./go.d.plugin -d -m pgbouncer

**Comment by Ancairon** [comment]
Thanks for raising this @pmbmarques, I am taking a look asap.

**Comment by Ancairon** [comment]
This is fixed by https://github.com/netdata/go.d.plugin/pull/1246
