### ISSUE TITLE
[BUG]: wrong version of google-gtag plugin 

### ISSUE THREAD

**Issue by tkatsoulas** [netdata/learn#1749]
### Doc Page link

pass

### Description

During docusaurus build we receive this error

```
1:28:33 AM: [ERROR] Invalid docusaurus-plugin-google-tag-manager version 2.4.0.
1:28:33 AM: All official @docusaurus/* packages should have the exact same version as @docusaurus/core (2.3.1).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
[ERROR] Invalid docusaurus-plugin-google-gtag version 2.4.0.
1:28:34 AM: All official @docusaurus/* packages should have the exact same version as @docusaurus/core (2.3.1).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
```

**Comment by Ancairon** [comment]
I think this PR is related https://github.com/netdata/learn/pull/1576 and must've added this. @andrewm4894 in that case.

**Comment by andrewm4894** [comment]
Yeah this was related to needing to run GA UA tag and the new GA4 tag in parallel for a bit. 

We are now only on GA4 so might be able to just use that as I think GAUA has now been sunsetted.

I'll take a look and make a fresh PR to try clean this up.

**Comment by andrewm4894** [comment]
Background is that version of the plugin was the only one that supports multiple tags for this very reason.

**Comment by andrewm4894** [comment]
Context

https://github.com/facebook/docusaurus/issues/7221
