### ISSUE TITLE
[Feedback]: PFSense+ 23.05.1 - pkg update issue

### ISSUE THREAD

**Issue by evanhfox** [netdata/learn#1774]
### Doc Page link

https://learn.netdata.cloud/docs/installing/pfsense

### Description

To be clear, this isn't a netdata issue specifically.

Following the steps outlined in the PFSense install guide, the initial enabling and update of the FreeBSD Repo requires an update to `pkg` which is seemingly incompatible with PFSense+ 23.05.01-RELEASE:

`New version of pkg detected; it needs to be installed first.
The following 1 package(s) will be affected (of 0 checked):

```
Installed packages to be UPGRADED:
	pkg: 1.19.1_1 -> 1.20.5 [FreeBSD]`
```

Once the install takes place, `pkg` can no longer be used due to a missing library.

`ld-elf.so.1: Shared object "libssl.so.30" not found, required by "pkg"`

This library needs to be added or pkg rolled back to 1.19.1_1.

Again, not a Netdata specific issue but it may be wise to add a caution in the PFSense Netdata install guide to warn users.

I would **love** a bonefide PFSense Netdata Package from the PFSense Repo!

**Comment by Ancairon** [comment]
Hey @evanhfox :wave: I discussed this matter internally and we believe it would be best to open an issue to the pfsense community, as it is indeed not a Netdata specific issue.

I see that the instructions are community maintained, so I will review them and possibly add a message, to mention that they work specifically with pfsense CE.
