### ISSUE TITLE
[Feedback]: Limitation of Netdata with Docker

### ISSUE THREAD

**Issue by zebulon501** [netdata/learn#1779]
### Doc Page link

https://learn.netdata.cloud/docs/installing/docker

### Description

First of all, thanks for this grate product! It allows to observe a system in its deepest details in live!

The [Install Netdata with Docker](https://learn.netdata.cloud/docs/installing/docker) page should highlight the differences and limitations of installing Netdata directly on the host versus in a container. Monitoring of devices (with `smartd` and `nvme-cli`) is possible with more privileges on the containers and more mounts. Some plugins are not present in the image, which is understandable but should be put in evidence.

**Comment by ilyam8** [comment]
Hi, @zebulon501. You are right. All these limitations are collector-related. 

>  is possible with more privileges on the containers and more mounts
>  Some plugins are not present in the image

We will need to update the collectors' readmes (e.g. setup step).


>  installing Netdata directly on the host versus in a containe

At the moment I think it is common sense that all collectors that use binaries to gather data don't work inside a Docker container.
