### ISSUE TITLE
[Feedback]: kickstart.sh hash appears to be incorrect

### ISSUE THREAD

**Issue by garymoon** [netdata/learn#1826]
### Doc Page link

https://learn.netdata.cloud/docs/installing/one-line-installer-for-all-linux-systems

### Description

At the bottom of the page (as an aside, it would be good to make this more prominent) there is a one-liner for verifying the integrity of `kickstart.sh` from `https://my-netdata.io/kickstart.sh`. The hash used on the page appears to match the script as it was three weeks ago (see [here](https://github.com/netdata/netdata/blob/21539122d57536bd30bf92d9e62fa6cb25142c85/packaging/installer/kickstart.sh)) instead of the most recent version (see [here](https://github.com/netdata/netdata/blob/062484b66ae9c09778acad96580b68d911517ae5/packaging/installer/kickstart.sh)) which is currently live on `my-netdata.io`.

**Comment by tkatsoulas** [comment]
I will change the workflow (spli the ingest workflow from the update of checksum ) to reduce the latency period. 

Thanks for the feedback
