### ISSUE TITLE
[Feedback]: no /usr/libexec/netdata, so alert test instructions don't work

### ISSUE THREAD

**Issue by timdonovanuk** [netdata/learn#1838]
### Doc Page link

https://learn.netdata.cloud/docs/alerting/notifications/agent-dispatched-notifications/ntfy#:~:text=ntfy%20(pronounce%3A%20notify)%20is,to%20run%20your%20own%20server.

### Description

I used the Netdata one line installer provided by the Cloud dashboard, on Debian instance (Proxmox 8) I'm setting up alerting. The path /usr/libexec/netdata does not exist, so I'm not sure how to test alerting or indeed it will work.

**Comment by timdonovanuk** [comment]
I guess the documentation should all read /opt/netdata/usr/libexec/netdata/plugins.d?

**Comment by Ancairon** [comment]
Hey @timdonovanuk :wave: 

> I also had to manually copy /etc/netdata/health_alarm_notify.conf to /opt/netdata/etc/netdata/health_alarm_notify.conf.

For this I would @netdata/agent-sre, and then take the feedback internally if there is indeed a fix needed on the integration.
