### ISSUE TITLE
[Feedback]: Building a static binary package (mention the need to update submodules)

### ISSUE THREAD

**Issue by aidanharris** [netdata/learn#1876]
### Doc Page link

https://learn.netdata.cloud/docs/installing/static-binary-linux-packages

### Description

># Building a static binary package
>
>To build the static binary 64-bit distribution package, run:
>
```
cd /path/to/netdata.git
./packaging/makeself/build-x86_64-static.sh
```

Suggested change:

```
cd /path/to/netdata.git
git submodule update --init --recursive
./packaging/makeself/build-x86_64-static.sh
```

It took me a while to realise why the build was failing.

**Comment by Ancairon** [comment]
Hey @aidanharris :wave: , thanks for the feedback! @netdata/agent-sre to evaluate that this is needed, and then I will make the change

**Comment by tkatsoulas** [comment]
Thanks for the feedback. hmmm this is a small part of the bigger issue (how you perform a cleanup/make sure that you are ready to build from source) let me give a little bit of thought and I will come back with a solution.
