### ISSUE TITLE
[Feedback]: Synology installation backup/restore

### ISSUE THREAD

**Issue by timrettop** [netdata/learn#1887]
### Doc Page link

https://learn.netdata.cloud/docs/installing/install-netdata-on-embedded-systems/synology

### Description

I've noticed that DSM Updates overwrite or replace parts of the core OS and /opt/netdata is removed.  

I'd like to build a set of scripts that back up important files and reinstalls netdata with its associated claim data so that it will recover cleanly from a DSM upgrade.  At boot, the script would run, check for the existence of /opt/netdata, if its missing, it'd restore the appropriate files, reinstall netdata, and restore the permissions and rc.netdata files as needed. 

I think I can do all that, but I'm wondering if I'm taking the right approach, and if so, what files should I backup and restore? 
/opt/netdata/etc 
/opt/netdata/var/lib/netdata
/opt/netdata/var/log/netdata
/opt/netdata/var/cache/netdata

how about plugins and webfiles?

**Comment by timrettop** [comment]
Maybe an alternative could be to install elsewhere than /opt so that the data is not overwritten, then just run a boot script to check rc.netdata, etc.  Anyone have thoughts on that alternative?

**Comment by Ancairon** [comment]
Hey @timrettop :wave: 
@netdata/agent-sre might be able to help in this

**Comment by tkatsoulas** [comment]
Hey @timrettop sorry for the late response, what you shared here
```
/opt/netdata/etc/netdata
/opt/netdata/var/lib/netdata
/opt/netdata/var/log/netdata
/opt/netdata/var/cache/netdata

```

will do the job

**Comment by tkatsoulas** [comment]
If you could find the time, please explore the possibility of a netdata Docker deployment on DSM (I don't have the necessary HW). I think will resolve any of your problems plus will provide you with all the essentials. If this works we need to update the instructions in such a way  that ( in Synology systems with decent resources) deploy netdata via docker
