### ISSUE TITLE
[Feedback]: add container instructions for nvidia_smi plugin

### ISSUE THREAD

**Issue by Petemir** [netdata/learn#1921]
### Doc Page link

https://learn.netdata.cloud/docs/data-collection/hardware-devices-and-sensors/nvidia-gpu

### Description

The original nvidia_smi module from python.d.plugin had extra details on how to make the host GPU(s) available to the container. Perhaps [those instructions](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nvidia_smi#docker) could be included in the documentation page for the new go version of the module.

**Comment by ilyam8** [comment]
Fixed in #17167
