### ISSUE TITLE
[Feedback]: alloc or save?

### ISSUE THREAD

**Issue by grinapo** [netdata/learn#1935]
### Doc Page link

https://learn.netdata.cloud/docs/configuring/optimizing-metrics-database/database-modes-for-parent-child-setups

### Description

> **alloc**, like ram but it uses calloc() and does not support [KSM](https://learn.netdata.cloud/docs/configuring/optimizing-metrics-database/database-modes-for-parent-child-setups#ksm). This mode is the fallback for all others except none.

vs.

> On a [Parent - Child](https://learn.netdata.cloud/docs/streaming/understanding-how-streaming-works) setup, use [db].mode = dbengine on the parent to increase retention, and a more resource-efficient mode like, dbengine with light retention settings, **save**, ram, or none for the children to minimize resource utilization.

(It's `alloc` I think, and `save` may be a remnant of old times.)

**Comment by Ancairon** [comment]
Hey @grinapo! Indeed, we removed the `save` option, so I prepared a PR to fix this, thanks!
