### ISSUE TITLE
[Feedback]: Link on Rest API page is down

### ISSUE THREAD

**Issue by ouarIT** [netdata/learn#1962]
### Doc Page link

https://learn.netdata.cloud/docs/rest-api/

### Description

I can´t access to the Netdata Agent's API through swagger UI. I'm using the link on the page
![image](https://github.com/netdata/learn/assets/73901833/a855be3d-9c88-43fb-9228-175ca5f1b335)

**Comment by Ancairon** [comment]
This has been fixed by https://github.com/netdata/learn/pull/1965!
