### ISSUE TITLE
[Feedback]: PagerDuty Centralized Cloud Notifications not working

### ISSUE THREAD

**Issue by zoete** [netdata/learn#1992]
### Doc Page link

https://learn.netdata.cloud/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/pagerduty

### Description

I provided the PagerDuty integration key from the service, clicked test and I get a "Something went wrong" alert in the bottom right corner. I then clicked Ok, then clicked "Test your notification settings" and I get the same error.

This is with `eu.pagerduty.com`

**Comment by Ancairon** [comment]
Hey @zoete we'll be looking into this asap internally.

It is best to create any cloud-related-bug reports in the [designated GH repo](https://github.com/netdata/netdata-cloud) to ensure they are properly prioritized. This repo does not serve as a bug report hub, mostly bugs related to Learn should be reported here :smile:

**Comment by zoete** [comment]
Hey, do you want me to mirror the issue there or would that be redundant at this point?

**Comment by juacker** [comment]
Hey @zoete,

We've released a new version that addresses the issue you reported.

We've added a new parameter to the integration settings. This allows you to specify the specific alerts events URL for your Pagerduty region. You can find this new parameter within your integration configuration, I'm sending you an example:

![image](https://github.com/netdata/learn/assets/2930882/b0b3376f-26a4-479c-8593-ac24f67cbde3)



Please, let us know if this resolves your issue

**Comment by zoete** [comment]
Hey @juacker 

Thank you for the quick fix, I can confirm it works!
