### ISSUE TITLE
[Feedback]: Netdata Cloud Themes

### ISSUE THREAD

**Issue by Cris70** [netdata/learn#1999]
### Doc Page link

https://learn.netdata.cloud/docs/dashboards-and-charts/choose-your-netdata-cloud-theme

### Description

I like very much the light theme as shown on this page, but what I see is different: the left pane background is not dark, it's colored with a pale shade of gray.
Either the page is outdated, or there's something wrong in the theme itself.

Here is what I see:
![immagine](https://github.com/netdata/learn/assets/5107224/f2f7d6d9-1782-45ce-9516-03fed088084f)

**Comment by Ancairon** [comment]
Hey @Cris70! Thank you for your feedback, we have an ongoing effort on updating screenshots or removing them on places that evolve rapidly, and the screenshot is outdated in a matter of weeks.

Feedback appreciated!

**Comment by Cris70** [comment]
Great, thank you @Ancairon
