### ISSUE TITLE
[Feedback]: Custom dashboards on OSS Agent

### ISSUE THREAD

**Issue by huntson** [netdata/learn#2002]
### Doc Page link

https://learn.netdata.cloud/docs/dashboards-and-charts/custom-dashboards

### Description

There doesn't seem to be any information for how to do the same thing on a Netdata Agent without the cloud.

**Comment by tkatsoulas** [comment]
Hello @huntson. Custom dashboards is a Netdata Cloud feature.
![Screenshot from 2024-03-17 11-21-52](https://github.com/netdata/learn/assets/12612986/206de7ad-1641-41db-9577-3098575ebb3c)



source: https://www.netdata.cloud/pricing/
