### ISSUE TITLE
[Feedback]: Home/Initiate login URL renders incorrectly

### ISSUE THREAD

**Issue by bc-ble** [netdata/learn#2086]
### Doc Page link

https://learn.netdata.cloud/docs/netdata-cloud/authentication-&-authorization/cloud-authentication-&-authorization-integrations/oidc

### Description

The "Home/Initiate login URL" link on the OIDC setup page renders incorrectly but the actual link is correct.
If someone copies the URL from the page and isn't paying close attention it won't work for setting up OIDC.

![image](https://github.com/netdata/learn/assets/131190231/0ed8511b-60f5-476a-a56a-30a38468d197)

**Comment by Ancairon** [comment]
Hey @bc-ble thanks for the nice catch, I think I know what is going on, the link is not a markdown link, so the `&` is not escaped properly and gets turned into that symbol most likely. Will prepare a fix!

**Comment by bc-ble** [comment]
Looks great now, thanks for fixing it!
