### ISSUE TITLE
[Feedback]: MD5 checksum failed, cannot update

### ISSUE THREAD

**Issue by GavinPhotography** [netdata/learn#2132]
### Doc Page link

https://learn.netdata.cloud/docs/netdata-agent/installation/linux/

### Description

System Version: Ubuntu 24.04 LTS (GNU/Linux 6.8.0-35-generic x86_64)

I just prepared to install the latest version of netdata following the guide in the official website. But something wrong occured during my installation.
The correct MD5 checksum value showed in the guide is "afa8a47cde0c7a3e5a7a94ee5857c012", but the value of my downloaded one is "88f2ea4c9e048656b1bb779c3af883d0". Here are the logs during my operations.
`root@gavin-Aspire-4752:/var/cache/netdata# curl https://get.netdata.cloud/kickstart.sh > /tmp/netdata-kickstart.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 92126  100 92126    0     0  47689      0  0:00:01  0:00:01 --:--:-- 47684
root@gavin-Aspire-4752:/var/cache/netdata# md5sum /tmp/netdata-kickstart.sh
88f2ea4c9e048656b1bb779c3af883d0  /tmp/netdata-kickstart.sh`

By the way, the netdata in one of my servers remains at the version v1.45.6. Even if I have been trying to update it through the kickstart script, it still doesn't work.

**Comment by Ancairon** [comment]
Hey @GavinPhotography most likely you ran it in the slim window where we changed the checksum and needed to merge the updates on Learn, I would suggest trying again and letting us know what happens.
