### ISSUE TITLE
[Feedback]: Change of Teams Webhook functionality

### ISSUE THREAD

**Issue by etec-masterofsynapse** [netdata/learn#2158]
### Doc Page link

https://learn.netdata.cloud/docs/alerts-&-notifications/notifications/centralized-cloud-notifications/microsoft-teams

### Description

Microsoft is changing how webhooks work: https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

Unless Netdata is already compatible with the new message body the Workflow App in Teams needs, there is development effort to be made.

**Comment by Ancairon** [comment]
https://github.com/netdata/netdata/pull/18224
