### ISSUE TITLE
Saving cgroup.swap_read & cgroup.swap_write calls recorded by eBPF swap

### ISSUE THREAD

**Issue by Bar-dia** [netdata/learn#2220]
### Doc Page link

https://learn.netdata.cloud/docs/collecting-metrics/ebpf/ebpf-swap

### Description

Hi, I want to save the recorded the number of swap.read and swap.write calls inside a cgroup that is captured by eBPF swap in netdata into a txt, csv or a chart. How can I do that?
I want to record the swap usage (read / write) with high resolution in my computer for research purposes.

**Comment by Ancairon** [comment]
Hey @Bar-dia as this repo is mainly suited to issues about the content and deployment of our documentation, I would suggest opening this issue on our Discord server or on our Discussions on the main repo!

If what you mean is that you want to capture a metric that Netdata produces, you can do so by using the `data` [API call of Netdata](https://learn.netdata.cloud/api#/data) :point_right:  [I have an example](https://github.com/Ancairon/SRS/blob/custom-datasets/custom_datasets/generateCSV.py) (research purposes too!)

**Comment by Bar-dia** [comment]
Hi, thanks for your reply. I have submitted my question in discord server!

Thanks,

Bardia Alidoust
