### ISSUE TITLE
Iteration #2 of Documentation feedback form

### ISSUE THREAD

**Issue by kickoke** [netdata/learn#894]
The documentation feedback form works, but there is room for improvement:

### Implement a field that tracks page URL
When a user submits feedback, we currently see the following information: 
![image](https://user-images.githubusercontent.com/13576110/153259603-9c0f0ea7-353b-4fbe-8c5b-68eb8d6bb611.png)

We see the thumbs up or down and even the feedback text, but we lose the information of where the feedback was given. It would be good to have a hidden field that automatically pulls the current URL.  

### Implement another layer of spam-filtering
I would go for the honeypot option, as they lure in bots and the field isn't visible to the standard user. 
More about [spam filtering in the Netlify docs](https://docs.netlify.com/forms/spam-filters/)

**Comment by kickoke** [comment]
@novykh Do you have capacity this month to take another look at this? 🥺👉👈

**Comment by novykh** [comment]
We can add this in the form as last input - under the textarea.
```
               <p class="invisible">
                    <label>
                      Don't fill this out if you're human:{' '}
                      <input
                        name="botfield"
                        onChange={e =>
                          setFormData(prevFormData => ({
                            ...prevFormData,
                            [e.target.name]: e.target.value,
                          }))
                        }
                      />
                    </label>
                  </p>
```

**Comment by kickoke** [comment]
#899 Handles this issue

**Comment by kickoke** [comment]
Thanks to @novykh's help, I was able to implement the current URL and a honeypot field for bots. 
However, we will still probably need to mark spam so that the netlify algorithm learns.

For example, we have received this entry: 
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/13576110/154241812-d628de85-80c8-49d0-9e78-08d05b91410e.png">

Now, I am not sure if there are some people getting paid for posting spam, but I'd say: Let's see how it goes over the course of the next week and if we need to do more about spam filtering.

**Comment by novykh** [comment]
Hmmm I thought there was already a mechanism for that that's why we implemented it that way. We can fix that on our side, coming back with a code block for you to test out :)

**Comment by novykh** [comment]
Change this:
```
const handleSubmit = e => {
    e.preventDefault();
    fetch("/", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: encode({ "form-name": "thumbs-voting", ...formData })
    })
      .then(() => setFeedback(true))
      .catch(() => setFeedback(true));
  };
```
To this:
```
const handleSubmit = e => {
    e.preventDefault();
    const { botfield, ...rest } = formData;
    
    if (botfield) {
       setFeedback(true)
       return;
    }
    
    fetch("/", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: encode({ "form-name": "thumbs-voting", ...rest })
    })
      .then(() => setFeedback(true))
      .catch(() => setFeedback(true));
  };
```

**Comment by kickoke** [comment]
Just a question, shouldn't `setFeedback` be false if the bot fills out a bot field, so the entry doesn't get written to Netlify?

**Comment by novykh** [comment]
`setFeedback` just shows the "Thank you for your feedback", we can change it to "Thank you for your feedback, you kind bot"

**Comment by kickoke** [comment]
Okay, then I'll leave it as is. :)
