### ISSUE TITLE
Update Docusaurus to newest version

### ISSUE THREAD

**Issue by kickoke** [netdata/learn#922]
### Problem

Currently, we are using Docusaurus 2.0.0 beta. To make use of some features that have been added in later versions, we want to update to Docusaurus 2.0.0 beta17. However, the theme was adapted with custom code ("swizzled" is the docusaurus lingo).

However, these custom components prevent us to seamlessly update to the latest version. 
Especially the CSS has broken. 
I was able to resurrect most features, see PR #921. 
However the main issues are: 
* Styling: Dark theme is broken
* DocSidebar: The table of contents (also called sidebar) looks a bit different. For example, on the current version of learn.netdata.cloud there are custom dividers, which are not in the vanilla code. The current file contains a loot of custom code, and I couldn't make sense of it
Vanilla code: https://github.com/netdata/learn/tree/staging1/src/theme/DocSidebar
Current code: https://github.com/netdata/learn/tree/master/src/theme/DocSidebar

### More information/ resources
Branch: staging1
Preview: https://staging1--netdata-docusaurus.netlify.app/docs/

About custom code (swizzling): 
📄 [Swizzled Components in Learn](https://github.com/netdata/learn#custom-swizzled-docusaurus-components)
📄 [Docusaurus Docs - Sidebar](https://docusaurus.io/docs/sidebar)
📄 [Docusaurus docs - Styling](https://docusaurus.io/docs/styling-layout)
📄 [Infima design system](https://infima.dev/docs/getting-started/introduction)

Custom code: 
📁 [Customized Theme components](https://github.com/netdata/learn/tree/staging1/src/theme)
📁 [Custom CSS](https://github.com/netdata/learn/tree/staging1/src/css)
Components can have custom CSS as well, but then it is in the styles.module.css file that lies in the same folder as the component. 

@novykh Can you check who can help us out? :)

**Comment by tkatsoulas** [comment]
[Minor] This https://github.com/netdata/learn/commit/f28bcd57f4be0a6463964239629ccdd1ca293369 commit says beta.14, it's a typo. it's beta.15

**Comment by kickoke** [comment]
@tkatsoulas  I think in the meantime they even released beta.16. We could update to the latest version while we are in this limbo...

**Comment by tkatsoulas** [comment]
@kickoke we will probably have to go to beta.17 since this effort is still in progress. I am looking forward to a stable not beta release from docusaurus 

> <div class="margin-bottom--lg" style="box-sizing: border-box; margin-bottom: 2rem !important; color: rgb(28, 30, 33); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 class="anchor anchorWithHideOnScrollNavbar_tWSU" id="next" style="box-sizing: border-box; color: var(--ifm-heading-color); font-family: var(--ifm-heading-font-family); font-weight: var(--ifm-heading-font-weight); line-height: var(--ifm-heading-line-height); margin: var(--ifm-heading-margin-top) 0 var(--ifm-heading-margin-bottom) 0; font-size: var(--ifm-h3-font-size); scroll-margin-top: 0.5rem;">Current version (Stable)<a class="hash-link" href="https://docusaurus.io/versions#next" title="Direct link to heading" style="box-sizing: border-box; transition: opacity var(--ifm-transition-fast); color: var(--ifm-link-color); text-decoration: var(--ifm-link-decoration); opacity: 0; padding-left: 0.5rem; user-select: none;">​</a></h3><p style="box-sizing: border-box; margin: 0 0 var(--ifm-paragraph-margin-bottom);">Here you can find the documentation for current released version.</p>
>
> 2.0.0-beta.17 | Documentation | Release Notes
> -- | -- | --
>
> </div>Current version (Stable)
>Here you can find the documentation for current released version.
>
>2.0.0-beta.17	[Documentation](https://docusaurus.io/docs)	[Release Notes](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.17)
>Next version (Unreleased)
> Here you can find the documentation for work-in-process unreleased version.
>
> 2.0.0-beta.18 🚧	[Documentation](https://docusaurus.io/docs/next)
> Past versions (Not maintained anymore)
> Here you can find documentation for previous versions of Docusaurus.
>
> 2.0.0-beta.16	[Documentation](https://docusaurus.io/docs/2.0.0-beta.16)	[Release Notes](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.16)
> 2.0.0-beta.15	[Documentation](https://6220d0362c028b000827f851--docusaurus-2.netlify.app/docs/2.0.0-beta.15)	[Release Notes](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.15)
> source: https://docusaurus.io/versions

**Comment by kickoke** [comment]
Solved by #963
