### ISSUE TITLE
Missing guide summary for step 1

### ISSUE THREAD

**Issue by DanTheMediocre** [netdata/learn#924]
This is a relatively minor issue but I would like to try taking first steps in contributing to the Netdata project and noticed that the [Guides](https://learn.netdata.cloud/guides/) page has summaries for all the guides except Step 1 of the step-by-step guide.
I would like to add the summary that is already present as part of the step 0 guide, same as with the other parts

![Capture1](https://user-images.githubusercontent.com/19797393/156651935-743d1fb8-d549-40cf-8f6a-c9221af04a80.PNG)
![Capture2](https://user-images.githubusercontent.com/19797393/156651952-2639930a-2a7b-4cce-9f95-9d2286b236c2.PNG)

**Comment by DShreve2** [comment]
Good catch, @DanTheMediocre! Thank you! Hope to see more contributions from you in the future.

**Comment by kickoke** [comment]
Thank you! 
I just merged your PR. :)

Warm regards from the Netdata docs team.
