### ISSUE TITLE
Netdata Cloud & Agent: Add documentation for new search bar feature

### ISSUE THREAD

**Issue by kickoke** [netdata/learn#942]
TL; DR: 
The Cloud and the Agent will get a search bar to make finding charts easier. 
https://github.com/netdata/product/issues/2328

Point of contact for further info: @hugovalente-pm

**Comment by hugovalente-pm** [comment]
@kickoke just an update, we are doing our final tests and QA of this feature on staging.
we plan to release it this week.

btw, was creating this entry on prismic to have it appears as news our app - will get @jlbriston ok for the review https://netdata-news.prismic.io/documents~b=working&c=unclassified&l=en-us/YkMGWhAAACEAAlSS/

the news on the app are these
![image](https://user-images.githubusercontent.com/82235632/160620098-5264fecb-617c-4736-b1e6-e02b7a3881fc.png)

**Comment by kickoke** [comment]
@DShreve2 Can you check if the search bar qualifies as "sleigh" (too obvious to the user so it doesn't need docs) or if it needs an explanantion?
