### ISSUE TITLE
Update netdata repo README

### ISSUE THREAD

**Issue by kickoke** [netdata/learn#947]
## Description

The netdata/netdata repository readme is outdated. It also needs to be improved in terms of structure and content. Some of the content in the readme is very good but isn't available in the documentation.

## Research

- [ ] Existing documents: Get familiar with existing documents: https://github.com/netdata/marketing/pull/248

## Production

- [ ] Existing documents: Refine document - Add new structure
- [ ] Rework the integration interactive picture
- [ ] Get technical review
- [ ] Get peer review

## Publication

- [ ] Merge PR

**Comment by cakrit** [comment]
We need to look at https://github.com/netdata/netdata/edit/master/docs/getting-started/introduction.md and https://github.com/netdata/netdata/edit/master/README.md to probably make them the same document.
