### ISSUE TITLE
Collector pages don't always say how to enable a collector

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/learn#955]
## Description

In the collector documentation over at [learn.netdata.cloud ](https://learn.netdata.cloud/) we do not have say how to enable a collector. it is mentioned in a separate section of the [docs](https://learn.netdata.cloud/docs/collect/enable-configure) but if the user is arriving from a Google serach for example and is directed to the specific collector page then it's not at all evident that there are extra steps that are required to enable the collector. 

Here's an example:

- [Postgres Python collector](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/postgres) 
 
![image](https://user-images.githubusercontent.com/24860547/160381941-84b5167c-8759-472c-a475-97aebc403174.png)
![image](https://user-images.githubusercontent.com/24860547/160381986-75c39531-726d-4bd8-997d-c75534c30281.png)

- What's not obvious to a new user is that they also need to run the extra steps listed here

![image](https://user-images.githubusercontent.com/24860547/160382165-9ce2035d-9b1f-47ea-8b92-ffb0347bf610.png)

![image](https://user-images.githubusercontent.com/24860547/160382255-410679c0-fd79-415b-9df5-0eb6a7586f4a.png)

**Comment by cakrit** [comment]
Related to #1477

**Comment by Ancairon** [comment]
Will be handled by https://github.com/netdata/product/issues/3169
