### ISSUE TITLE
Netdata Learn: More video and gif walkthroughs to accompany docs

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/learn#956]
## Description

It would be good to enrich our existing documentation for the most frequently visited sections with video walkthroughs which make it easier and quicker for the users to consume the information.

For example, if they are on a page about a particular collector, instead of only listing the chart names in text form we could have a small video or gif which actually shows the users what they would get.

P.S: Making the videos share-able would be cool too 😄

**Comment by shyamvalsan** [comment]
To prevent broken links - we could just embed YouTube walkthrough videos. 

For example, we were discussing within the ML team that we really need one of these for the new Anomaly Advisor feature. And it would make total sense to have that embedded in the relevant docs page.

**Comment by DShreve2** [comment]
We revisited this topic this week, and have landed on removing our Guides section in Learn, and replacing it with "Use cases" where we move our relevant "how to" blog types and embed or link our YouTube videos, making them searchable with tags so that users can find their individual answer.

**Comment by cakrit** [comment]
No videos in Learn, they are extremely hard to maintain.
