### ISSUE TITLE
Phase out Hangouts documentation

### ISSUE THREAD

**Issue by kickoke** [netdata/learn#969]
## Description

[](https://learn.netdata.cloud/docs/agent/health/notifications/hangouts)[](https://learn.netdata.cloud/docs/agent/health/notifications/hangouts)The Google hangouts notification system has already been phased out, but the documentation is still there.
[Send notifications to Google Hangouts | Learn Netdata](https://learn.netdata.cloud/docs/agent/health/notifications/hangouts)

Supply further description as needed. 

## Research

- [ ] Verify with an engineer if the docs are still needed. 
- [ ] Check if there are links to the page

## Production

- [ ] Delete document

## Publication

- [ ] Merge PR
- [ ] Approve ingest PR on netdata/learn
- [ ] Check for broken links in build log

**Comment by cakrit** [comment]
Doc removed temporarily, need to check if the notifications mechanism should be removed completely or if it works with google chat

**Comment by Ancairon** [comment]
@cakrit we should take a look at Stackpulse too, as it seems it is not maintained anymore.
